version: "3.9"

services:
  web:
    build:
      context: .
      shm_size: '2gb'
    container_name: flask_app
    env_file: .env
    ports:
      - "56567:56567"
    volumes:
      - ./tracking.py:/app/tracking.py
      - ./main.py:/app/main.py
    shm_size: '2gb'
